name: Try to run docker-compose up

on:
  - push
  - pull_request
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Give permissions to develop_init.sh file
      run: chmod +x ./.docker/develop_init.sh
    - name: Try to build docker compose
      run: docker-compose up -d --build
